### ISSUE TITLE
Latest version of shinylight breaks GeoplotR server

### ISSUE THREAD

**Issue by pvermees** [tim-band/shinylight#1]
When I update GeoplotR on the server using the latest version of shinylight, I get the following error message for all plots that involve a unit conversion from wt% to ppm or vice versa:

`argument "units" is missing, with no default`

Reverting to the penultimate release of shinylight fixes the issue. Strangely the problem only occurs on the server, and not offline!

**Comment by tim-band** [comment]
With v0.6, CART(HFS) doesn't work for a different reason, but all the rest work: CART(ratios), Ti-Si-Sr, Nb-Na-Sr, Ti-Sm-V, Ti-V, Ti-Zr-Y, Zr-Ti.
Same thing with v0.7. Has this been fixed with a new GeoplotR?

**Comment by pvermees** [comment]
Seems to all work fine now, including CART (HFS). Cheers!
